# Generated by Django 5.0 on 2024-01-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='blogimg',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
        migrations.AddField(
            model_name='blog',
            name='blogimg1',
            field=models.ImageField(blank=True, null=True, upload_to='blogpic1'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blogimg2',
            field=models.ImageField(blank=True, null=True, upload_to='blogpic1'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blogimg3',
            field=models.ImageField(blank=True, null=True, upload_to='blogpic1'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blogimg4',
            field=models.ImageField(blank=True, null=True, upload_to='blogpic1'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blogimg5',
            field=models.ImageField(blank=True, null=True, upload_to='blogpic1'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blogimg6',
            field=models.ImageField(blank=True, null=True, upload_to='blogpic1'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blogimg7',
            field=models.ImageField(blank=True, null=True, upload_to='blogpic1'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blogimg8',
            field=models.ImageField(blank=True, null=True, upload_to='blogpic1'),
        ),
        migrations.AddField(
            model_name='blog',
            name='content1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content7',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content8',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='link',
            field=models.CharField(default=5, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='thumbleimage',
            field=models.ImageField(blank=True, null=True, upload_to='thumbleimg'),
        ),
    ]
