# Generated by Django 5.0 on 2024-01-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_project_remove_blog_blogimg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbleimage',
            field=models.ImageField(default=5454, upload_to='thumbleimg'),
            preserve_default=False,
        ),
    ]
