# Generated by Django 5.0 on 2024-01-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_blog_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='productname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
