# Generated by Django 5.0 on 2024-01-15 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_blog_productname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='number',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='reason',
        ),
    ]
