# Generated by Django 5.0 on 2024-01-15 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_homeimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeimg',
            old_name='homeimg',
            new_name='homeimage',
        ),
    ]
